//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEE_VOTE_DETAIL
    {
        public int IDEAS_ID { get; set; }
        public string COMMITTEE_MEMBER { get; set; }
        public Nullable<long> PROFIT_AMOUNT { get; set; }
        public Nullable<long> SAVING_RESOURCE_AMOUNT { get; set; }
        public Nullable<System.DateTime> SAVE_DATE { get; set; }
    
        public virtual IDEA IDEA { get; set; }
        public virtual USER USER { get; set; }
    }
}
