//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECTED_IDEA
    {
        public int IDEA_ID { get; set; }
        public int YEAR { get; set; }
        public int MONTH { get; set; }
    
        public virtual IDEA IDEA { get; set; }
    }
}
